version: '2'
services:
  base:
    build: .
    image: ropelive/twine
    restart: on-failure
    ports:
    - "4000:4000"
    command: /app/twine-server
    links:
    - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
